### ISSUE TITLE
this is don't work

### ISSUE THREAD

**Issue by Desintegrator** [claudiomadureira/screen-shield#1]
example also broken, only screenshot listener works

**Comment by Desintegrator** [comment]
ok, it works for video recording, but not for screenshots

**Comment by claudiomadureira** [comment]
Sorry, indeed the view is not protected against screenshots. The Apple framework only fires the event after the screenshot is taken. I tried to find any other framework using (c, c++, etc) but I didn't find any. I don't know how Netflix managed to do it, but it seemed so far that they implemented this feature themselves.

**Comment by Desintegrator** [comment]
got it, thank u for response
